// SPDX-License-Identifier: MIT
// Copyright (c) 2026 APC-Injector (GitHub: @ZYS-Create1024)

#pragma once

#define IOCTL_SET_LOADLIBRARY_ADDRESS \
CTL_CODE( \
	FILE_DEVICE_UNKNOWN, \
	0x800, \
	METHOD_BUFFERED, \
	FILE_WRITE_ACCESS)

#define IOCTL_SET_DLL_PATH \
CTL_CODE( \
	FILE_DEVICE_UNKNOWN, \
	0x801, \
	METHOD_BUFFERED, \
	FILE_WRITE_ACCESS)
/////////////////////////////////////////////////////////////
#define IOCTL_TURN_ON_PROCESS_CALLBACK \
CTL_CODE( \
	FILE_DEVICE_UNKNOWN, \
	0x802, \
	METHOD_BUFFERED, \
	FILE_ANY_ACCESS)

#define IOCTL_TURN_OFF_PROCESS_CALLBACK \
CTL_CODE( \
	FILE_DEVICE_UNKNOWN, \
	0x803, \
	METHOD_BUFFERED, \
	FILE_ANY_ACCESS)
/////////////////////////////////////////////////////////////
#define IOCTL_PUSH_WHITE_LIST_ITEM \
CTL_CODE( \
	FILE_DEVICE_UNKNOWN, \
	0x804, \
	METHOD_BUFFERED, \
	FILE_WRITE_ACCESS)


#define IOCTL_REMOVE_WHITE_LIST_ITEM \
CTL_CODE( \
	FILE_DEVICE_UNKNOWN, \
	0x805, \
	METHOD_BUFFERED, \
	FILE_WRITE_ACCESS)

#define IOCTL_QUERY_WHITE_LIST_ITEM \
CTL_CODE( \
	FILE_DEVICE_UNKNOWN, \
	0x806, \
	METHOD_BUFFERED, \
	FILE_READ_ACCESS)